### ISSUE TITLE
Prereqs

### ISSUE THREAD

**Issue by wallarug** [robotics-masters/mm1-hat-arduino#2]
This is what I have installed:
Arduino AVR Boards (not needed)
Arduino SAM Boards (32-bits ARM Cortex-M0+) 1.6.20
Arduino SAMD Beta Boards (32-bits ARM Cortex-M0+) 1.6.25
Adafruit SAMD Boards 1.2.9
Robo HAT Boards by Robotics Masters 0.0.3

**Comment by wallarug** [comment]
#include "sam.h"

installing the beta samd boards fixes the error

**Comment by hmic** [comment]
The 0.0.4 branch updates all tools and fixes missing dependencies.

**Comment by wallarug** [comment]
Excellent.  Thanks Hans.
